version: '3'
services:
    myapp:
        image: ${app_reg_image}
        ports:
            - 3000:3000
        #restart: unless-stopped
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${mongo_user}
            - MONGO_INITDB_ROOT_PASSWORD=${mongo_pass}
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongo_user}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongo_pass}
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - "mongodb"
        restart: unless-stopped

volumes:
    mongo-data:
        driver: local
