version: '3'
services:
    myapp:
        #image: 999331468001.dkr.ecr.eu-central-1.amazonaws.com/my-app:1.5.2
        #image: ${aws_ecr}/my-app:1.5.1
        image: miltosdev/dwd-app:v1.3
        ports:
            - 3000:3000
        #restart: unless-stopped
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - "mongodb"
        restart: unless-stopped

volumes:
    mongo-data:
        driver: local
